/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Tenants {
  createdAt: Generated<Timestamp>;
  externalReferenceId: string | null;
  id: Generated<string>;
  name: string;
  slug: string;
  updatedAt: Generated<Timestamp>;
}

export interface DB {
  tenants: Tenants;
}

/**
 * Database schema type alias
 * Alias for DB interface to match common naming convention
 */
export type Database = DB;
