# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: 'en-US'
tone_instructions: 'Be thorough and focus on security and maintainability'
reviews:
  profile: 'chill'
  high_level_summary: true
  suggested_reviewers: true
  auto_assign_reviewers: true
auto_review:
  enabled: true
  drafts: false
  labels:
    - 'feature'
    - 'bugfix'
    - '!wip'
  path_filters:
    - '!node_modules/**'
    - '!dist/**'
    - '!build/**'
    - 'src/**'
    - 'tests/**'
tools:
  gitleaks:
    enabled: true
  semgrep:
    enabled: true
  checkov:
    enabled: true
  eslint:
    enabled: true
  ruff:
    enabled: true
  golangci-lint:
    enabled: true
    config_file: '.golangci.yml'
  hadolint:
    enabled: true
  yamllint:
    enabled: true
  actionlint:
    enabled: true
finishing_touches:
  docstrings:
    enabled: true
  unit_tests:
    enabled: true
pre_merge_checks:
  title:
    mode: 'error'
    requirements: 'Title should be concise and descriptive'
  description:
    mode: 'warning'
  docstrings:
    mode: 'warning'
    threshold: 80
chat:
  auto_reply: true
knowledge_base:
  code_guidelines:
    enabled: true
    filePatterns:
      - '**/.cursorrules'
      - '.github/copilot-instructions.md'
      - '**/CLAUDE.md'
      - '**/CODING_STANDARDS.md'
