{{- if .Values.keycloak.adminClient.enabled }}
apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: Client
metadata:
  name: {{ .Values.keycloak.adminClient.id }}-client
spec:
  providerConfigRef:
    name: {{ .Values.keycloak.providerConfigRef }}

  # Write client credentials to Kubernetes secret
  writeConnectionSecretToRef:
    name: antithesis-admin-credentials
    namespace: {{ .Values.namespace }}

  forProvider:
    realmId: {{ .Values.keycloak.realm.name }}
    clientId: {{ .Values.keycloak.adminClient.id }}
    name: {{ .Values.keycloak.adminClient.name }}
    description: {{ .Values.keycloak.adminClient.description }}

    # Client access type - confidential for client credentials
    accessType: confidential

    # Flow settings for service account (client_credentials grant)
    standardFlowEnabled: false          # No authorization code flow
    implicitFlowEnabled: false          # No implicit flow
    directAccessGrantsEnabled: false    # No password grant
    serviceAccountsEnabled: true        # ENABLE service accounts for client_credentials

    # No redirect URIs needed for service accounts
    validRedirectUris: []
    webOrigins: []
{{- end }}
