{{- if .Values.keycloak.oidcClient.enabled }}
apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: Client
metadata:
  name: {{ .Values.keycloak.oidcClient.id }}-client
spec:
  providerConfigRef:
    name: {{ .Values.keycloak.providerConfigRef }}

  # Write client credentials to Kubernetes secret
  writeConnectionSecretToRef:
    name: antithesis-oidc-credentials
    namespace: {{ .Values.namespace }}

  forProvider:
    realmId: {{ .Values.keycloak.realm.name }}
    clientId: {{ .Values.keycloak.oidcClient.id }}
    name: {{ .Values.keycloak.oidcClient.name }}
    description: {{ .Values.keycloak.oidcClient.description }}

    # Client access type - confidential for server-side apps
    accessType: confidential

    # Flow settings for OIDC authentication
    standardFlowEnabled: true          # Authorization Code flow
    implicitFlowEnabled: false         # Don't allow implicit flow
    directAccessGrantsEnabled: false   # Don't allow direct access (password grant)
    serviceAccountsEnabled: false      # This is NOT a service account

    # Valid redirect URIs for OAuth callback
    validRedirectUris:
      {{- range .Values.keycloak.oidcClient.redirectUris }}
      - {{ . | quote }}
      {{- end }}

    # Valid post-logout redirect URIs
    validPostLogoutRedirectUris:
      {{- range .Values.keycloak.oidcClient.postLogoutRedirectUris }}
      - {{ . | quote }}
      {{- end }}

    # Web origins for CORS
    webOrigins:
      {{- range .Values.keycloak.oidcClient.webOrigins }}
      - {{ . | quote }}
      {{- end }}
{{- end }}
