{{- if .Values.keycloak.realm.enabled }}
apiVersion: realm.keycloak.crossplane.io/v1alpha1
kind: Realm
metadata:
  name: {{ .Values.keycloak.realm.name }}-realm
spec:
  providerConfigRef:
    name: {{ .Values.keycloak.providerConfigRef }}
  forProvider:
    realm: {{ .Values.keycloak.realm.name }}
    enabled: true
    displayName: {{ .Values.keycloak.realm.displayName }}

    # Basic authentication settings
    registrationAllowed: {{ .Values.keycloak.realm.registrationAllowed }}
    loginWithEmailAllowed: {{ .Values.keycloak.realm.loginWithEmailAllowed }}
    resetPasswordAllowed: {{ .Values.keycloak.realm.resetPasswordAllowed }}
    verifyEmail: {{ .Values.keycloak.realm.verifyEmail }}

    # Custom realm attributes
    {{- if .Values.keycloak.realm.organizationsEnabled }}
    attributes:
      organizationsEnabled: "{{ .Values.keycloak.realm.organizationsEnabled }}"
    {{- end }}

    # Token lifespans
    accessTokenLifespan: {{ .Values.keycloak.realm.accessTokenLifespan | quote }}

    # Session settings
    ssoSessionIdleTimeout: {{ .Values.keycloak.realm.ssoSessionIdleTimeout | quote }}
    ssoSessionMaxLifespan: {{ .Values.keycloak.realm.ssoSessionMaxLifespan | quote }}
{{- end }}
